name: Elixir CI

on: pull_request

jobs:
  formatter:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
      - name: Check formatting
      - run: mix format --check-formatted

  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test

services:
  postgres:
    image: postgres:9.6